name: Extract Secret
on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret in Base64
        env:
          # YAHAN 'YOUR_SECRET_NAME' KO APNE SECRET KE NAAM SE REPLACE KAREIN
          SECRET_VALUE: ${{ secrets.YOUR_SECRET_NAME }}
        run: |
          echo "Yeh raha aapka Base64 Encoded Secret:"
          echo -n "$SECRET_VALUE" | base64
